### ISSUE TITLE
Dragging a maximised window

### ISSUE THREAD

**Issue by Torvin** [emoacht/WpfMonitorAware#10]
My app's main window has `WindowState="Maximized"` property set. When I grab it by the window title and start dragging for the first time, `MonitorAware` does not properly resize it. Here is the log from the debug output:

```
ENTERSIZEMOVE
SIZE
MOVE
MOVE
MOVE
MOVE
DPICHANGED: 96 -> 144
Monitor DPI: 96-96 -> 144-144
MOVE
MOVE
MOVE
MOVE
Window DPI: 96-96 -> 144-144
Old Size: 800-600
SIZE
SIZE
New Size: 2904-1211
```

What happens here (I think) is window gets un-maximised when I start dragging it (the first `SIZE` in the log) to `800-600` (I can confirm that this is the correct restored window size). Then, when I drag it into the monitor with a 1.5 DPI it incorrectly uses the maximised window's size rather then restored size: `800-600 * 1.5` should have been `1200-900`, not the huge `2904-1211`.

If I restore the window once before dragging it - the bug goes away.

**Comment by emoacht** [comment]
Thank you for reporting.
I think this issue is solved in new version.
